# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
# A Tera template to be rendered as the changelog's footer.
# See https://keats.github.io/tera/docs/#introduction
header = """
<!-- LTeX: language=en-FR -->
# Changelog\n
All notable changes to this project will be documented in this file. See [conventional commits](https://www.conventionalcommits.org/) for commit guidelines.\n
"""
# A Tera template to be rendered for each release in the changelog.
# See https://keats.github.io/tera/docs/#introduction
# ## [[{{ version | trim_start_matches(pat="v") }}]]($REPO/compare/{{ previous.version }}..{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
body = """
---
{% if version %}\
    {% if previous.version %}\
        ## [\\<{{ version | trim_start_matches(pat="v") }}\\>]($REPO/releases/{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }} <small><small><small>[(compare)]($REPO/compare/{{ previous.version }}..{{ version }})</small></small></small>
    {% else %}\
        ## [\\<{{ version | trim_start_matches(pat="v") }}\\>]($REPO/releases/{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
    {% endif %}\
{% else %}\
    ## \\<unreleased\\> <small><small><small>[(compare)]($REPO/compare/{{ previous.version }}..main)</small></small></small>
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits
    | filter(attribute="scope")
    | sort(attribute="scope") %}
        - **({{commit.scope}})**{% if commit.breaking %} **⚠️ breaking!** {% endif %} \
            {{ commit.message }} {%- for link in commit.links %} {%- if link.text is starting_with("#") %} <small>[**\\[{{ link.text }}\\]**]({{ link.href }})</small> {%- endif %} {%- endfor %} <small><small>[({{ commit.id | truncate(length=7, end="") }})]($REPO/commit/{{ commit.id }})</small></small>
    {%- endfor -%}
    {% raw %}\n{% endraw %}\
    {%- for commit in commits %}
        {%- if commit.scope -%}
        {% else -%}
            - {% if commit.breaking %} **⚠️ breaking!** {% endif %}\
                {{ commit.message }} {%- for link in commit.links %} {%- if link.text is starting_with("#") %} <small>[**\\[{{ link.text }}\\]**]({{ link.href }})</small> {%- endif %} {%- endfor %} <small><small>[({{ commit.id | truncate(length=7, end="") }})]($REPO/commit/{{ commit.id }})</small></small>
        {% endif -%}
    {% endfor -%}
{% endfor %}\n
"""
# A Tera template to be rendered as the changelog's footer.
# See https://keats.github.io/tera/docs/#introduction
footer = """
<!-- generated by git-cliff -->
"""
# Remove leading and trailing whitespaces from the changelog's body.
trim = true
# postprocessors
postprocessors = [
    # Replace the placeholder `<REPO>` with a URL.
    { pattern = '\$REPO', replace = "https://github.com/MagicTINTIN/binary-sparse-matrices" }, # replace repository URL
]

[git]
# Parse commits according to the conventional commits specification.
# See https://www.conventionalcommits.org
conventional_commits = true
# Exclude commits that do not match the conventional commits specification.
filter_unconventional = true
# Split commits on newlines, treating each line as an individual commit.
split_commits = false
# An array of regex based parsers to modify commit messages prior to further processing.
commit_preprocessors = [
    # Replace issue numbers with link templates to be updated in `changelog.postprocessors`.
    # { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}]($REPO/issues/${2}))"},
    # { pattern = " \\+", replace = " \n\nother: "},
]
# An array of regex based parsers for extracting data from the commit message.
# Assigns commits to groups.
# Optionally sets the commit's scope and can decide to exclude commits from further processing.
commit_parsers = [
    { message = "^feat", group = "<!-- 00 -->🚀 Features" },
    { message = "^fix", group = "<!-- 01 -->🐛 Bug Fixes" },
    { message = "^perf", group = "<!-- 02 -->⚡ Performance" },
    { message = "^rework", group = "<!-- 03 -->🔧 Rework" },
    { message = "^refactor", group = "<!-- 04 -->🚜 Refactor" },
    { message = "^chore\\(version\\):", skip = true },
    { message = "^chore", group = "<!-- 05 -->⚙️ Miscellaneous Chores" },
    { message = "^data", group = "<!-- 05 -->⚙️ Miscellaneous Chores" },
    { body = ".*security", group = "<!-- 06 -->🛡️ Security" },
    { message = "^revert", group = "<!-- 07 -->⏪ Revert" },
    { message = "^doc\\(changelog\\)", skip = true },
    { message = "^doc", group = "<!-- 08 -->📚 Documentation" },
    { message = "^style", group = "<!-- 09 -->🎨 Style" },
    { message = "^clean", group = "<!-- 09 -->🎨 Style" },
    { message = "^test", group = "<!-- 10 -->🧪 Tests" },
    { message = "^build", group = "<!-- 11 -->🏗️ Build" },
    { message = "^debug", group = "<!-- 11 -->🏗️ Build" },
    # { message = "^debug", group = "<!-- 12 -->📃 Debug" },
    { message = "^ci", group = "<!-- 12 -->✅ Continuous Integration" },
    { message = "^FIX???", skip = true },
    { message = "^wip", skip = true },
    # { message = ".*", group = "<!-- 11 -->💼 Other" },
]

link_parsers = [
    { pattern = "#(\\d+)", href = "https://github.com/MagicTINTIN/binary-sparse-matrices/issues/$1"},
]
# Exclude commits that are not matched by any commit parser.
filter_commits = false
# Order releases topologically instead of chronologically.
topo_order = false
# Order of commits in each group/release within the changelog.
# Allowed values: newest, oldest
sort_commits = "oldest"
